### PR TITLE
chore(trezor): Upgrade to Trezor Connect v9

### PR DESCRIPTION
**Pull request by sime**
Hello from the Trezor Team,

We are working on [Trezor Connect v9](https://github.com/trezor/trezor-suite/tree/develop/packages/connect) and would like to test the library against your app.

Sadly `yarn test` doesn't have any tests?

### CODE REVIEW

**Comment by Ivshti** [comment]
Hey @sime 

this repo is running slightly behind the private repo where the live development happens, we will check the compatibility of this PR against the latest development branch and get back to you

as for tests, we do have a manual testing procedure, and also integration tests in the latest development branch. We can test if for you

**Comment by sime** [comment]
Thanks for the heads up

**Comment by Mysticalgirl007** [comment]
Me too thank you this is what we need for now 😔

**Comment by Hannsek** [comment]
Hello @Ivshti, 
Just letting you know that we have released Connect v9. It is now GA. https://www.npmjs.com/package/@trezor/connect/v/9.0.0

**Comment by Ivshti** [comment]
@Hannsek @sime we have implemented the new trezor connect, loosely based on this PR, in our main private repo. Thanks for your contribution!

**Comment by sime** [comment]
@Ivshti Shout out when it's released.

**Pull request closed without merging**
